BUZZWORD = [
    "action plan", "agenda", "agile", "alignment", "ambition",
    "API", "as-is", "autentisk", "autonomi", "benchmark",
    "best practice", "big-picture", "bringe i spil", "business case", "buy-in",
    "bygge videre på", "check-in", "circle back", "compliance", "cutting edge",
    "deep dive", "deliver", "disruption", "disruptiv", "diversitet",
    "driftsoptimering", "drill down", "growth", "driven", "dykke ned i",
    "dynamisk", "eksekvering", "end-to-end", "engagement", "EVP",
    "experimentation", "fail fast", "fleksibel", "fokusområde", "follow-up",
    "forandring", "forankring", "fremadskuende", "flow", "future",
    "målstregen", "game changer", "gap", "gevinst", "extra mile",
    "governance", "gå i dybden", "gå på tværs", "handlingsplan", "hands-off",
    "hands-on", "harmoni", "have fokus på", "helhedsorienteret", "helikopter",
    "high-level", "holistisk", "hybrid", "impact-driven", "implementering",
    "indsatsområde", "indsigt", "initiativ", "innovativ", "insights",
    "iteration", "iterere", "ja-hat", "journey", "key",
    "kigge ind i", "klarhed", "komme hele vejen rundt", "komme i mål", "komme rundt om",
    "kommerciel", "kompetence", "konkurrence", "kontinuerlig", "kunde",
    "kvalitet", "lavthængende frugter", "lean", "ledelse", "legacy systems",
    "leverance", "lifecycle", "loop in", "low-hanging fruit", "loyalitet",
    "loyalty", "løfte blikket", "løsningsorienteret", "management", "markedsposition",
    "merværdi", "metrics", "milepæl", "milestones", "mindset",
    "momentum", "MVP", "målepunkter", "målretning", "målstyring",
    "målsætning", "need-to-know", "needs-based", "netværk", "next generation",
    "next level", "next steps", "no brainer", "nytænkning", "offboarding",
    "onboarding", "operational", "optimering", "organisationskultur", "organisatorisk",
    "outcome", "output", "overblik", "overligger", "ownership",
    "pain points", "paradigm shift", "paradigme", "parathed", "parkere",
    "people analytics", "people first", "people strategy", "people-centric", "performance",
    "potentiale", "prioritering", "proaktiv", "procesforbedring", "procesharmonisering",
    "procesoptimering", "processtandardisering", "product-market fit", "progression", "proof of concept",
    "POC", "prototype", "quick win", "raise the bar", "rejse",
    "ressource", "resultat", "roadmap", "ROI", "rollout",
    "sammenhæng", "scale-up", "scope", "se ind i", "ejerskab",
    "transparens", "single source of truth", "skabe fælles fodslag", "skalerbar", "snitflader",
    "sparring", "spille hinanden gode", "spor", "sprint", "status quo",
    "stejl læringskurve", "strategi", "strategisk", "strømline", "success",
    "sync", "synergi", "synlighed", "sælles retning", "sætte fokus på",
    "tage afsæt i", "helikopterperspektiv", "tage temperaturen", "takeaways", "target",
    "team spirit", "teknologisk gæld", "modenhed", "test and learn", "think outside the box",
    "tidslinje", "tilfredshed", "tillid", "timeline", "to-be",
    "touch base", "touchpoints", "traction", "transformation", "trust",
    "tværfunktionelt samarbejde", "indsats", "tværgående samarbejde", "tænke ud af boksen", "understøtte",
    "unlock growth", "unlock potential", "use cases", "value", "vidensdeling",
    "virksomhedskultur", "vision", "vækst", "værdi", "work-life balance",
    "workflow", "zoome ind", "zoome ud", "åben dialog", "åbne op",
    "økosystem"
]

FORSLAG = {
    "action plan": "handlingsplan",
    "agenda": "dagsorden",
    "agile": "arbejde i korte forløb",
    "alignment": "fælles forståelse",
    "ambition": "mål",
    "API": "forbindelse mellem systemer",
    "as-is": "nuværende situation",
    "autentisk": "oprigtig",
    "autonomi": "selvbestemmelse",
    "benchmark": "sammenligningsgrundlag",
    "best practice": "afprøvet metode",
    "big-picture": "helhed",
    "bringe i spil": "bruge",
    "business case": "begrundelse og økonomi",
    "buy-in": "opbakning",
    "bygge videre på": "videreudvikle",
    "check-in": "kort status",
    "circle back": "vende tilbage til",
    "compliance": "overholdelse af regler",
    "cutting edge": "nyeste løsning",
    "deep dive": "grundig gennemgang",
    "deliver": "levere",
    "disruption": "stor forandring",
    "disruptiv": "markant forandrende",
    "diversitet": "forskellighed",
    "driftsoptimering": "forbedring af driften",
    "drill down": "undersøge nærmere",
    "growth": "vækst",
    "driven": "motiveret",
    "dykke ned i": "undersøge",
    "dynamisk": "foranderlig",
    "eksekvering": "gennemførelse",
    "end-to-end": "fra start til slut",
    "engagement": "involvering",
    "EVP": "det virksomheden tilbyder medarbejderne",
    "experimentation": "afprøvning",
    "fail fast": "afprøv tidligt",
    "fleksibel": "kan tilpasses",
    "fokusområde": "prioriteret område",
    "follow-up": "opfølgning",
    "forandring": "konkret ændring",
    "forankring": "fast indarbejdelse",
    "fremadskuende": "med fokus på fremtiden",
    "flow": "arbejdsgang",
    "future": "fremtid",
    "målstregen": "målet",
    "game changer": "afgørende ændring",
    "gap": "forskel",
    "gevinst": "fordel",
    "extra mile": "gøre en ekstra indsats",
    "governance": "ansvar og beslutningsregler",
    "gå i dybden": "undersøge grundigt",
    "gå på tværs": "samarbejde mellem afdelinger",
    "handlingsplan": "plan med konkrete opgaver",
    "hands-off": "begrænset indblanding",
    "hands-on": "praktisk deltagelse",
    "harmoni": "god sammenhæng",
    "have fokus på": "prioritere",
    "helhedsorienteret": "med blik for hele opgaven",
    "helikopter": "overblik",
    "high-level": "overordnet",
    "holistisk": "samlet",
    "hybrid": "kombineret",
    "impact-driven": "styret af ønskede resultater",
    "implementering": "indførelse",
    "indsatsområde": "område vi arbejder med",
    "indsigt": "viden",
    "initiativ": "forslag eller handling",
    "innovativ": "ny",
    "insights": "viden",
    "iteration": "arbejdsrunde",
    "iterere": "forbedre i flere omgange",
    "ja-hat": "positiv tilgang",
    "journey": "forløb",
    "key": "vigtig",
    "kigge ind i": "undersøge",
    "klarhed": "tydelighed",
    "komme hele vejen rundt": "undersøge alle relevante dele",
    "komme i mål": "færdiggøre",
    "komme rundt om": "behandle",
    "kommerciel": "forretningsmæssig",
    "kompetence": "færdighed",
    "konkurrence": "kamp om kunderne",
    "kontinuerlig": "løbende",
    "kunde": "den konkrete kundegruppe",
    "kvalitet": "konkret kvalitetskrav",
    "lavthængende frugter": "nemme forbedringer",
    "lean": "fjerne unødvendigt arbejde",
    "ledelse": "konkret ledelsesansvar",
    "legacy systems": "ældre systemer",
    "leverance": "resultat eller produkt",
    "lifecycle": "levetid",
    "loop in": "inddrage",
    "low-hanging fruit": "nemme forbedringer",
    "loyalitet": "fastholdelse",
    "loyalty": "fastholdelse",
    "løfte blikket": "se på helheden",
    "løsningsorienteret": "fokuseret på konkrete løsninger",
    "management": "ledelse",
    "markedsposition": "placering på markedet",
    "merværdi": "konkret fordel",
    "metrics": "måltal",
    "milepæl": "delmål",
    "milestones": "delmål",
    "mindset": "tankegang",
    "momentum": "fremdrift",
    "MVP": "første brugbare version",
    "målepunkter": "det vi måler",
    "målretning": "tilpasning til målgruppen",
    "målstyring": "styring efter konkrete mål",
    "målsætning": "mål",
    "need-to-know": "nødvendig information",
    "needs-based": "baseret på behov",
    "netværk": "konkrete forbindelser",
    "next generation": "ny version",
    "next level": "forbedret niveau",
    "next steps": "næste opgaver",
    "no brainer": "oplagt valg",
    "nytænkning": "ny løsning",
    "offboarding": "afslutning for medarbejdere",
    "onboarding": "introduktion af nye medarbejdere",
    "operational": "praktisk drift",
    "optimering": "forbedring",
    "organisationskultur": "måden organisationen arbejder på",
    "organisatorisk": "i organisationen",
    "outcome": "resultat",
    "output": "det der produceres",
    "overblik": "samlet oversigt",
    "overligger": "kravniveau",
    "ownership": "ansvar",
    "pain points": "konkrete problemer",
    "paradigm shift": "grundlæggende ændring",
    "paradigme": "grundlæggende tankegang",
    "parathed": "klar til",
    "parkere": "udsætte",
    "people analytics": "analyse af medarbejderdata",
    "people first": "hensyn til medarbejderne",
    "people strategy": "medarbejderstrategi",
    "people-centric": "med fokus på medarbejderne",
    "performance": "resultater",
    "potentiale": "mulighed",
    "prioritering": "valg af det vigtigste",
    "proaktiv": "handle på forhånd",
    "procesforbedring": "forbedring af arbejdsgangen",
    "procesharmonisering": "ensretning af arbejdsgange",
    "procesoptimering": "forbedring af arbejdsgangen",
    "processtandardisering": "fælles arbejdsgang",
    "product-market fit": "om produktet løser kundernes behov",
    "progression": "udvikling",
    "proof of concept": "afprøvning af idéen",
    "POC": "afprøvning af idéen",
    "prototype": "prøveversion",
    "quick win": "hurtig forbedring",
    "raise the bar": "hæve kravene",
    "rejse": "forløb",
    "ressource": "tid, penge eller medarbejdere",
    "resultat": "konkret resultat",
    "roadmap": "tidsplan",
    "ROI": "økonomisk udbytte",
    "rollout": "gradvis indførelse",
    "sammenhæng": "konkret forbindelse",
    "scale-up": "udvide",
    "scope": "opgavens omfang",
    "se ind i": "undersøge",
    "ejerskab": "ansvar",
    "transparens": "åbenhed",
    "single source of truth": "ét fælles datagrundlag",
    "skabe fælles fodslag": "blive enige",
    "skalerbar": "kan udvides",
    "snitflader": "kontaktpunkter",
    "sparring": "faglig drøftelse",
    "spille hinanden gode": "hjælpe hinanden",
    "spor": "arbejdsområde",
    "sprint": "kort arbejdsperiode",
    "status quo": "den nuværende situation",
    "stejl læringskurve": "meget at lære på kort tid",
    "strategi": "plan",
    "strategisk": "langsigtet",
    "strømline": "forenkle",
    "success": "succes",
    "sync": "koordinere",
    "synergi": "fordel ved samarbejde",
    "synlighed": "tydelig information",
    "sælles retning": "fælles mål",
    "sætte fokus på": "prioritere",
    "tage afsæt i": "basere på",
    "helikopterperspektiv": "overblik",
    "tage temperaturen": "undersøge den aktuelle situation",
    "takeaways": "vigtigste pointer",
    "target": "mål",
    "team spirit": "samarbejde i gruppen",
    "teknologisk gæld": "problemer fra tidligere tekniske valg",
    "modenhed": "hvor udviklet noget er",
    "test and learn": "afprøve og lære",
    "think outside the box": "finde en anden løsning",
    "tidslinje": "tidsplan",
    "tilfredshed": "hvor tilfredse folk er",
    "tillid": "konkret tegn på tillid",
    "timeline": "tidsplan",
    "to-be": "ønsket situation",
    "touch base": "tage en kort samtale",
    "touchpoints": "kontaktpunkter",
    "traction": "fremgang",
    "transformation": "større forandring",
    "trust": "tillid",
    "tværfunktionelt samarbejde": "samarbejde mellem fagområder",
    "indsats": "konkret handling",
    "tværgående samarbejde": "samarbejde mellem afdelinger",
    "tænke ud af boksen": "finde en anden løsning",
    "understøtte": "hjælpe",
    "unlock growth": "skabe vækst",
    "unlock potential": "udnytte muligheder",
    "use cases": "eksempler på brug",
    "value": "værdi",
    "vidensdeling": "dele viden",
    "virksomhedskultur": "måden virksomheden arbejder på",
    "vision": "ønsket fremtid",
    "vækst": "konkret stigning",
    "værdi": "konkret fordel",
    "work-life balance": "balance mellem arbejde og fritid",
    "workflow": "arbejdsgang",
    "zoome ind": "undersøge detaljerne",
    "zoome ud": "se på helheden",
    "åben dialog": "direkte samtale",
    "åbne op": "fortælle eller gøre tilgængeligt",
    "økosystem": "netværk af virksomheder og systemer"
}